<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/1/7
 * Time: 10:34
 */
namespace app\api\controller;


header('Access-Control-Allow-Origin:*'); // *代表允许任何网址请求
header('Access-Control-Allow-Methods:POST,GET,OPTIONS,DELETE'); // 允许请求的类型
header('Access-Control-Allow-Headers: Content-Type,Content-Length,Accept-Encoding,X-Requested-with, Origin');
header('Access-Control-Allow-Headers:content-type,Authorization');
header("Access-Control-Request-Headers:Origin,X-Requested-With,content-Type,Accept,Authorization");

use think\Controller;
use think\Request;
class Apis extends Controller{
      protected  $request = '';

      public function _initialize()
     {
         parent::_initialize(); // TODO: Change the autogenerated stub
         $this->request = Request::instance(); //实例化 request 对象

         if($this->request->isPost()){
             $header = $this->request->header('');
             $this->check_token($header['authorization']);//测试接收token
         }else{
             exit();
         }
     }

      /**
      * 检查token
      * @token string
      */
      public function check_token($token){
              if(empty($token) || !isset($token)){
                  $this->jsonMsg(400,'token不存在');
              }
              $apitoken = $token; //客户端token
              //对于客户端传递的token加密对比
              $server_token = md5(md5($apitoken)); //服务端token
              //2f7b52aacfbf6f44e13d27656ecb1f59
              if(md5(md5($apitoken)) !== $server_token){
                  $this->jsonMsg(403,'token不正确');
              }

      }

      /**
       * 组装json数据
       * @code 状态码
       * @msg  提示信息
       * @data 返回数据
       */
      public function jsonMsg($code,$msg='',$data=''){
            $datas['code'] =$code;
            $datas['msg']  =$msg;
            $datas['data'] =$data;

            echo  json_encode($datas);
            exit();
      }

}