<?php
namespace app\api\controller;


use think\Controller;
use app\v1\service\Exampleservice;
use app\v1\service\Workservice;
use app\v1\service\Keywordsservice;

class Index extends Controller{

    /** 构造**/
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin: *");//允许所有请求
    }

    /**
     * 客户案例
     * 测试
     */
    public function customerlist(){
        if($this->request->isPost()){
            $page = input('post.page','','int');
            $size = input('post.size','','int');
            $list = Exampleservice::instance()->getcustmoerlist($page,$size);

            if(!empty($list) || isset($list)){
                return json(['code'=>2000,'msg'=>'success','data'=>$list]);
            }

            if(empty($list) || !isset($list)){
                return json(['code'=>4000,'msg'=>'数据为空！']);
            }
        }
        return false;
    }

    /**
     * 案例详情
     * 测试
     */
    public function customergetinfo(){
         if($this->request->isPost()){
             $id = input('post.id','','int');
             if(empty($id) || !isset($id) || is_null($id)||$id <=0){
                 return json(['code'=>4003,'msg'=>'数据请求不合法','data'=>null]);
             }

             $info = Exampleservice::instance()->getcustmoerbyid($id);

             if(empty($info) || !isset($info)){
                 return json(['code'=>4000,'msg'=>'请求数据为空','data'=>null]);
             }

             return json(['code'=>2000,'msg'=>'success','data'=>$info]);
         }
         return false;
    }

    /**
     * 新闻资讯列表页
     * @title 搜索关键字
     * @page  当前页数
     * @size  每页显示条数
     */
    public function newslist(){
        if($this->request->isPost()){
             $title = input('post.title','','int');
             $page  = input('post.page','','int');
             $size  = input('post.size','','int');

             $list = Workservice::instance()->getworklist($title,$page,$size);

             if(empty($list) || !isset($list)){
                 return json(['code'=>4000,'msg'=>'请求数据为空','data'=>null]);
             }
             return json(['code'=>2000,'msg'=>'success','data'=>$list]);

        }
        return false;
    }

    /** 获取新闻详情**/
    public function getnewsinfo(){
        if($this->request->isPost()){
           $id = input('post.id','','int');

           if(empty($id) || !isset($id) || is_null($id) || $id <= 0){
               return json(['code'=>4003,'msg'=>'数据类型不合法！','data'=>null]);
           }
           $info = Workservice::instance()->getIdInfo($id);

           if(empty($info) || !isset($info)){
               return json(['code'=>4000,'msg'=>'数据为空','data'=>null]);
           }

           return json(['code'=>2000,'msg'=>'success','data'=>$info]);
        }
        return false;
    }

    /**
     * 热门关键字列表
     */
    public function getkeywordlist(){
        if($this->request->isPost()){
             $list = keywordsservice::instance()->getkeywordlist();

             if(empty($list) || !isset($list)){
                 return json(['code'=>4000,'msg'=>'请求数据为空','data'=>null]);
             }

             return json(['code'=>2000,'msg'=>'success','data'=>$list]);
        }

        return false;
    }
}